### ISSUE TITLE
Memory explodes at z ~ 3

### ISSUE THREAD

**Issue by andreufont** [rainwoodman/MP-Gadget#92] opened 2017-09-07 15:51 UTC
I was able to compile and run the code on a couple of computers, and in both of them I'm finding the same issue:
- I can run the default Lya simulation in the examples folder without problem. 
- When I multiply by 2 the number of particles / mesh cells, it runs fine until z ~ 3 and then it crashes complaining about memory. 

_Task=13: Not enough memory in mymalloc_fullinfo() to allocate 7.57067e+07 MB for variable 'PMmesh' at pm_alloc()/petapm.c/line 679 (FreeBytes=8445.21 MB)_

If I look a bit up, I can see lost of messages like: 

_[ 000991.25 ] Task 13: enlarging node size from 1.14556e+06 to 1.17506e+06, due to particle of type 0 at 67839 -42711.1 -597525 id=838023_

Not sure what is going on... but I believe I should not run out of memory for such small simulation... The settings are:
paramfile.gadget:Nmesh = 256
paramfile.genic:Nmesh = 128 # This is the size of the FFT grid used to 
paramfile.genic:Ngrid = 128 # number of particles per grid direction.
paramfile.genic:Nsample = 128 # k space sampling upper limit

By the way, I'm still very confused about the different "N" above... I just assumed that the defaults were sensible and scaled all of them by a factor of two.

**Comment by andersdot** [comment] 2017-09-07 15:56
I'm having the same problem

**Comment by rainwoodman** [comment] 2017-09-07 21:42
Looks like that particle has gone too far to a very negative location. Let me test this is this the master branch?

**Comment by rainwoodman** [comment] 2017-09-07 22:35
The simulation looked OK. Here is a visual of the gas projection the snapshot before it crashed:

![image](https://user-images.githubusercontent.com/138060/30188139-bd5328b8-93e1-11e7-8039-073614bc1636.png)

I think it is related to a known issue (tree and particle sequence out of sync when the dynamics is tense -- hence affected the higher res run -- I assume you didn't increase the boxsize?). 

We have worked around in the bluetides-ii branch and also completely fixed in the statictree branch. I'll work something out and let you guys know.

**Comment by rainwoodman** [comment] 2017-09-07 23:59
I can confirm that the statictree branch as of a5d50c4302169b515dcc5bdbcdfcda9ae652704a works fine with the 128**3 Ngrid test.

Here is a z=1.5 visual of gas density.
![image](https://user-images.githubusercontent.com/138060/30190235-d1be0230-93ed-11e7-9deb-3238f4931d0a.png)

**Comment by andersdot** [comment] 2017-09-08 09:09
Thanks for the incredibly quick response ! I'll give it a try

**Comment by andersdot** [comment] 2017-09-08 09:28
Oh, I'm still confused by the paramfile setting for the resolutions. Here are the default settings in your repo:

paramfile.gadget:Nmesh = 128
paramfile.genic:Nmesh = 64 # This is the size of the FFT grid used to
paramfile.genic:Ngrid = 64 # number of particles per grid direction.
paramfile.genic:Nsample = 64 # k space sampling upper limit

I just assumed that the defaults were sensible and scaled all of them up by a factor of two. It's confusing that there is a resolution parameter in the gadget paramfile, and that it is 2x what's set in the IC generator. Can you give a brief description of what they do?

**Comment by andreufont** [comment] 2017-09-08 09:37
@rainwoodman I'm trying now statictree branch, I should have a result soon. Thanks!

@andersdot I've been doing some research, and I believe I half understand it now. 

In GenIC:
- Ngrid: number of particles, that one is easy. 
- Nmesh + Nsample: options to add more Fourier modes beyond fundamental mode or Nyquist (by padding zeros and/or sub-sampling cells, I guess), so that the power that goes into the particles is less affected by numerical artifacts.

In Gadget: 
- you can not change number of particles, that is set by GenIC. 
- Nmesh: sets the number of cells in the grid used to compute the long-range forces. 

But yes, I have no idea about the reasonable values for these, so keeping the same ratio than in the example for now is probably the best option :-)

**Comment by andreufont** [comment] 2017-09-08 10:55
@rainwoodman, the run crashed at z=4 while trying to print the first snapshot, with the following message: 
Task 2: Particles not sorted by type during IO

I checked that the same crashes when using the default configuration file (Ngrid=64). 

It is probably related to a recent commit I saw about this, right? I am using the latest version of statictree. Should I be using an older one?

**Comment by andreufont** [comment] 2017-09-08 15:59
With a different setting of box size / resolution, it went all the way to z=2 and printed the results successfully. For instance, with the following settings it works:

In genIC: 
Nmesh = 64 # This is the size of the FFT grid used to 
Ngrid = 64 # number of particles per grid direction.
Nsample = 64 # k space sampling upper limit
BoxSize = 5000   # Periodic box size of simulation

In gadget: 
Nmesh = 128

But then, something crazy happens when we try to double box size at same resolution:  

In genIC: 
Nmesh = 128 # This is the size of the FFT grid used to 
Ngrid = 128 # number of particles per grid direction.
Nsample = 128 # k space sampling upper limit
BoxSize = 10000   # Periodic box size of simulation

In gadget: 
Nmesh = 256

The simulation ran fine all the way to z=2, and then it continued to z=1.58. That would be "fine", unless at that point it goes back to z=2 and starts a loop running from z=2 to z=1.58 non-stop!
For instance:
_grep "Begin Step" test_gadget.out 
...
[ 008664.96 ] Begin Step 506, Time: 0.387031, Redshift: 1.58377, Nf = 00000004194304, Systemstep: 0.00186041, Dloga: 0.00481846, status: 
[ 008694.31 ] Begin Step 507, Time: 0.33333, Redshift: 2.00003, Nf = 00000004194304, Systemstep: -0.0537012, Dloga: -0.149372, status: 
..._

This happens both on my desktop and on Hypatia.

**Comment by rainwoodman** [comment] 2017-09-08 18:30
Thanks for the testing!

On:  https://github.com/rainwoodman/MP-Gadget/issues/92#issuecomment-328073256
It appears you didn't get the head of statictree. The bug (not sorted by ptype) was fixed in 5136e9, as seen on https://github.com/rainwoodman/MP-Gadget/commits/statictree . Need to do a git pull to get these fixes!

On: https://github.com/rainwoodman/MP-Gadget/issues/92#issuecomment-328144024
The not sorted bug disappeared, probably because you did a git pull somewhere between these 6 hours.

The going backward thing needs some care -- but looks like it depends on the step size. (resolution changes the step size) I'll try to reproduce it -- What is your output-list in the parameter file?

**Comment by rainwoodman** [comment] 2017-09-08 18:35
@andersdot : It is a good point that the parameters are confusing, because there is a dependency between the sensible values of Nmesh and Nsample against Ngrid in GenIC (Nmesh == Nsample == Ngrid), and the Nmesh in Gadget parameter file is decoupled from Nmesh in GenIC (Gadget's Nmesh is for long range gravity. GenIC's Nmesh is for Zeldovich) We will make Nmesh and Nsample 'optional' in GenIC.

**Comment by sbird** [comment] 2017-09-09 18:43
The going backwards thing is probably some edge case with the new timeline and snapshot outputs that are special in some way. Perhaps there is an output in the snapshot list which is after TimeEnd and the sorting is screwing up?

**Comment by rainwoodman** [comment] 2017-09-09 22:42
maybe it s interaction with check pointing? Notice andreu's run goes to a
few hours and the time is not particularly like a snapshot?



On Sep 9, 2017 11:43 AM, "Simeon Bird" <notifications@github.com> wrote:

The going backwards thing is probably some edge case with the new timeline
and snapshot outputs that are special in some way. Perhaps there is an
output in the snapshot list which is after TimeEnd and the sorting is
screwing up?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/rainwoodman/MP-Gadget/issues/92#issuecomment-328296095>,
or mute the thread

**Comment by sbird** [comment] 2017-09-10 20:22
Very possibly interaction with the automatic checkpointing. Also notice he has TimeMax set to 0.3333, as well as the last snapshot output time. So the code should really stop at z=2, but does not. I bet it is running to the next auto checkpoint and then trying to run backwards to the last real checkpoint.

**Closed** 2017-09-13 04:53 UTC
