### ISSUE TITLE
domain load balancing fails with imbalanced work.

### ISSUE THREAD

**Issue by rainwoodman** [rainwoodman/MP-Gadget#86] opened 2017-07-24 18:48 UTC
I am having trouble with the new domain code in a long test. It ran for 6 hours on 24 MPIs, 2 threads each and then crashed at z~0.5. It looks like the new domain is not load balancing correctly. Do you have any ideas before I blow a lot of time on a bisect? I suspect an inverted conditional, as it looks like there was a small imbalance initially which gradually got more severe as the simulation progressed, eventually crashing.

Here is the last step of the buggy run: All tasks above 19 look broken. It may be assigning the domain for tasks 20-23 to task 19.

==
[ 025489.96 ] Begin Step 2086, Time: 0.541833, Redshift: 0.845586, Nf = 00000000061521, Systemstep: 0.000304364, loga: 0.000561889, status:
[ 025489.96 ] TotNumPart: 0000134217728 SPH 0000000000000 BH 0000000000 STAR 0000000000000
[ 025489.96 ] Occupied: 0 1 2 3 4 5 dt
[ 025489.96 ] bin=15 0 74163885 0 0 0 0 0.00899022
[ 025489.96 ] bin=14 0 40198029 0 0 0 0 0.00449511
[ 025489.96 ] bin=13 0 16208717 0 0 0 0 0.00224756
[ 025489.96 ] X bin=11 0 61521 0 0 0 0 0.000561889
[ 025489.96 ] -----------------------------------
[ 025489.96 ] Total: 0 61521 0 0 0 0 Sum:
61521
[ 025489.96 ] Start force computation...
[ 025489.96 ] Begin tree force. (presently allocated=2919.41 MB)
[ 025490.16 ] tree is done.
[ 025490.16 ] force computation done.
[ 025490.58 ] domain decomposition... (presently allocated=2176.92 MB)
[ 025490.58 ] Allocated 170.667 MByte for top-level domain structure
[ 025490.61 ] use of 256 MB of temporary storage for domain decomposition... (presently allocated=2603.59 MB)
[ 025494.16 ] Before=209
[ 025494.16 ] Final NTopNodes = 673 per segment = 28.0417
[ 025494.16 ] NTopLeaves= 589 NTopNodes=673 (space for 5592406)
[ 025494.35 ] Expected segment cost 6.10072e+10
[ 025494.35 ] Created 25 segments for an expectation of 24
[ 025494.35 ] Largest deviations from average: work=5.01758 particle load=5.06507
[ 025494.35 ] desired memory imbalance=5.06507 (limit=11184810, needed=28325913)
[ 025494.35 ] Note: the domain decomposition is suboptimum because the ceiling for memory-imbalance is reached
[ 025494.35 ] Expected segment cost 5.59241e+06
[ 025494.35 ] Created 24 segments for an expectation of 24
[ 025494.35 ] Largest deviations from average: work=4.66919 particle load=4.61798
[ 025494.35 ] Balance breakdown:
[ 025494.35 ] Task: [ 0] work= 0.9660 particle load= 1.0121
[ 025494.35 ] Task: [ 1] work= 0.8931 particle load= 0.9556
[ 025494.35 ] Task: [ 2] work= 0.9201 particle load= 0.9627
[ 025494.35 ] Task: [ 3] work= 1.2798 particle load= 1.0768
[ 025494.35 ] Task: [ 4] work= 0.9347 particle load= 1.0197
[ 025494.35 ] Task: [ 5] work= 0.8289 particle load= 0.8778
[ 025494.35 ] Task: [ 6] work= 1.0903 particle load= 1.0894
[ 025494.35 ] Task: [ 7] work= 0.9149 particle load= 1.0027
[ 025494.35 ] Task: [ 8] work= 0.7697 particle load= 0.8700
[ 025494.35 ] Task: [ 9] work= 1.2430 particle load= 1.1067
[ 025494.35 ] Task: [ 10] work= 0.8185 particle load= 0.9430
[ 025494.35 ] Task: [ 11] work= 0.7261 particle load= 0.8511
[ 025494.35 ] Task: [ 12] work= 0.8953 particle load= 0.9215
[ 025494.35 ] Task: [ 13] work= 0.9632 particle load= 0.9073
[ 025494.35 ] Task: [ 14] work= 1.0987 particle load= 1.0802
[ 025494.35 ] Task: [ 15] work= 0.9875 particle load= 0.9274
[ 025494.35 ] Task: [ 16] work= 1.3722 particle load= 1.1317
[ 025494.35 ] Task: [ 17] work= 1.3737 particle load= 1.1914
[ 025494.35 ] Task: [ 18] work= 0.9074 particle load= 1.0297
[ 025494.35 ] Task: [ 19] work= 4.6692 particle load= 4.6180
[ 025494.35 ] Task: [ 20] work= 0.1035 particle load= 0.0976
[ 025494.35 ] Task: [ 21] work= 0.0000 particle load= 0.0000
[ 025494.35 ] Task: [ 22] work= 0.0011 particle load= 0.0010
[ 025494.35 ] Task: [ 23] work= 0.2432 particle load= 0.3269
[ 025494.35 ] desired memory imbalance=4.61798 (limit=11184810, needed=25825607)
[ 025494.35 ] No domain decomposition that stays within memory bounds is possible.

**Comment by rainwoodman** [comment] 2017-07-24 18:48
Converted from https://github.com/rainwoodman/MP-Gadget/pull/72#issuecomment-317312269

**Comment by rainwoodman** [comment] 2017-07-24 18:49
@sbird 
I think the parallel is OK -- there is no race. I disabled to for and it is still there.

**Comment by sbird** [comment] 2017-07-24 18:52
I thought it was not safe to do a += in an openmp for loop, because they are not guaranteed to be atomic? So you can end up losing half the bits of the addition. Or has that changed?

**Comment by rainwoodman** [comment] 2017-07-24 18:55
No. But they are working on different i's, thus there was no race.

**Comment by rainwoodman** [comment] 2017-07-24 18:57
There can be two possiblilities. one is a Leaf should have been refined, but it wasn't, such that it contained too many particles. Another is the assignment from Leaves to rank was broken. 
I lean toward the first scenario. How could that happen?

Isn't it a bit strange that there are many bin 11 particles but on bin 12 particles? Could you post me the full log file?

**Comment by sbird** [comment] 2017-07-24 18:58
That is just a copy-paste error: a line got deleted. There are many bin 12 particles.

**Comment by rainwoodman** [comment] 2017-07-24 18:59
OK. I am looking at the condition at line 1215.

**Comment by sbird** [comment] 2017-07-24 19:00
Full log from z=99:
[slurm-7588704.txt](https://github.com/rainwoodman/MP-Gadget/files/1170890/slurm-7588704.txt)

**Comment by sbird** [comment] 2017-07-24 19:01
Do you mean line 1215 of domain.c? That is the end of the file

**Comment by rainwoodman** [comment] 2017-07-24 19:03
Yes. I think it is line 1215. It stopped refinement too early.

We really should have a priority queue for the leaves, and always refine the largest known leaves.

**Comment by rainwoodman** [comment] 2017-07-24 19:03
Is it expensive for you to rerun with 1215 commented out? It may be that you can restart from a latest snapshot.

**Comment by sbird** [comment] 2017-07-24 19:04
It is cheap, but I am using statictree head, where domain.c is 1215 lines long, so I don't know which line you mean.

**Comment by rainwoodman** [comment] 2017-07-24 20:02
Oops. I read the wrong line number. PR #87

**Comment by sbird** [comment] 2017-07-24 20:11
So I could also have fixed this by increasing TOPNODEFACTOR or DomainOverDecompositionFactor, right?

**Comment by rainwoodman** [comment] 2017-07-24 20:27
Not necessarily. Increasing Topnodefactor means each leave will be smaller
and thus may still trigger a premature termination of the refinement before
the last few large leaves are refined. It is due to the current ordering of
the refinement doesn't prefer the large nodes first.

A priority queue may solve this. I am debating the form of it -- shall it
be a utility function that can be used in other parts of code? It also
means the local_refine shall use either GravCost or Count as the priority,
not both.

- Yu

**Comment by sbird** [comment] 2017-07-24 20:31
Do you not want to use GravCost if it is a load balance and count if a memory balance? So just a flag?

**Comment by sbird** [comment] 2017-07-24 20:32
I am checking results now

**Comment by rainwoodman** [comment] 2017-07-24 21:54
Still try one first, then fall back to the other.

**Comment by sbird** [comment] 2017-07-25 02:26
Your commit seems to have fixed the simulation that failed before, but I found an easy reproducer still. This one fails at the first timestep: I have increased DomainOverDecompositionFactor to 4.

In the first case I am running out_timestep3 with the second commit in the issue-86 cherry-picked.
[slurm-7643392.txt](https://github.com/rainwoodman/MP-Gadget/files/1171762/slurm-7643392.txt)
In the second case I changed the checks for countlimit and costlimit on domain.c:670 to 
be topNodes[i].Count <= 0.1*countlimit so that a lot more refinement happens:
[slurm-7643429.txt](https://github.com/rainwoodman/MP-Gadget/files/1171761/slurm-7643429.txt)

I think this indicates it is actually assigning Leaves to ranks incorrectly in some cases - they are certainly getting refined.

**Comment by sbird** [comment] 2017-07-25 13:16
The other test also crashed after a few hours - this didn't help that much.

**Comment by sbird** [comment] 2017-07-25 22:48
I see the problem - the last NTask TopNodes are assigned in order of key, one to each Task, which does not respect the load already on the tasks. Also there is a problem that at the moment neighbouring segments are not assigned to the same processor, which is bad for communication. What do you think of commit ca4cb0815 as a solution?

I think a pure priority queue would not be ideal because it would not keep close TopNodes on the same processor - maybe one should assign first in Key order and then, when the Task bins are filled above some level, switch to priority?

**Comment by rainwoodman** [comment] 2017-07-25 23:17
I have tried to come up with an algorithm that has fewer 'if's.

My old version does respect spatial locallity. A segment corresponds to
several continuous leaves, and the code runs to identify and assign such
segments till it is no longer possible.

The logic for assigning the last few to the ranks is to ensure each rank
gets at least one leaf.

If each leaf is only TotalCost / (NTask * Depfactor * TOPFactor), I don't
see why  assigning them to ranks individually gives a bad fluctuation.

Your double loop may make this a O(NLeaves * NProcess) operation. A heapq
makes it O(NLeaves * log2(NProcess))

**Comment by rainwoodman** [comment] 2017-07-25 23:18
Neighbouring segments are intentionally assigned to different ranks. For better cost balancing.

**Comment by rainwoodman** [comment] 2017-07-25 23:19
Could you post the first step crashing example?

**Comment by sbird** [comment] 2017-07-25 23:22
It is attached to comment: https://github.com/rainwoodman/MP-Gadget/issues/86#issuecomment-317610201

**Comment by sbird** [comment] 2017-07-25 23:25
I don't think the order of the algorithm is that important: NProcess and NLeaves are both << NPart.

The problem with the assignment of the final NTask TopNodes is that it does not take account of how much work is already on the Task, because curload is zeroed after each roundrobin - in fact after every roundrobin round the old code makes sure to assign at least one Segment to each task even if the task was full before. See my new code has curload[NTask] and stores the load in between assignments.

**Comment by rainwoodman** [comment] 2017-07-25 23:28
It matters. In BlueTides Nprocess = 100K and Nleaves = 2 Million.

**Comment by sbird** [comment] 2017-07-25 23:29
True. That is large.

**Comment by sbird** [comment] 2017-07-25 23:34
I could get rid of the second (inner) loop entirely though - I could store the task with the currently smallest load and just jump to it. That would be O(Nleaves) only.

**Comment by rainwoodman** [comment] 2017-07-25 23:38
I'll take a further look with a reusable priority queue. but got some other work on top of my priority queue right now.

**Comment by sbird** [comment] 2017-07-25 23:40
It's ok. This is actually very non-urgent. I am leaving tomorrow morning and will not have internet for a week or so, so we can put this on hold until I get back.

**Comment by rainwoodman** [comment] 2017-07-25 23:42
But afterwards you'll lost the currently smallest load, and computing it requires O(Np). If you are really into it, here is what I thought of a heapq:
```
typedef struct {
    int priority;
    int index;
} HeapQ;

typedef int (*q_priority_func)(int index, void * userdata);

int q_put(HeapQ * q, int index, q_priority_func qfunc);
int q_pop(HeapQ * q);
int q_peek(HeapQ * q);

```

**Comment by sbird** [comment] 2017-07-25 23:45
mm, that is true.

**Comment by sbird** [comment] 2017-08-08 18:33
I have been thinking about this, and I think what is needed actually are just some minor modifications to your current algorithm (which is O(Nleaves)), so that it tries to assign segments in one pass through the tasks, and small tweaks to the assignment conditions.

**Comment by sbird** [comment] 2017-08-10 16:19
Fixed now.

**Closed by sbird** 2017-08-10 16:19 UTC
